# Generated by Django 4.2.7 on 2023-12-09 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0006_studentpayment"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpaymentdetail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payment_details",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fee_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fee_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("overdue", "Over Due"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_id", models.CharField(max_length=100, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                            ("paypal", "Paypal"),
                        ],
                        default="stripe",
                        max_length=30,
                    ),
                ),
                ("is_notified", models.BooleanField(default=True)),
                (
                    "reciever",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.userpaymentdetail",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_payment_fees",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
