# Generated by Django 4.2.7 on 2023-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_userpaymentdetail_user_studentpayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentpayment",
            old_name="reciever",
            new_name="sender",
        ),
        migrations.AlterField(
            model_name="studentpayment",
            name="fee_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="userpaymentdetail",
            name="payment_qr",
            field=models.FileField(
                blank=True, null=True, upload_to="payments/paymentdetails/"
            ),
        ),
    ]
