# Generated by Django 4.2.6 on 2023-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
    ]
