# Generated by Django 4.2.6 on 2023-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_rename_student_studentprofile"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(fields=["user"], name="students_st_user_id_ccc8ad_idx"),
        ),
    ]
