# Generated by Django 4.2.6 on 2023-11-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_studentprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.URLField(
                default="https://res.cloudinary.com/ddoz9iuvk/image/upload/v1699871295/3d-illustration-person-with-sunglasses_23-2149436188_hukac4.jpg"
            ),
        ),
    ]
