# Generated by Django 4.2.6 on 2023-10-12 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_studentprofile_students_st_user_id_ccc8ad_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
    ]
