# Generated by Django 4.2.7 on 2023-11-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0006_job_application"),
        ("students", "0004_alter_studentprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_batch",
                to="institutes.batch",
            ),
        ),
    ]
