# Generated by Django 4.2.7 on 2023-12-02 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0007_application_status"),
        ("students", "0005_alter_studentprofile_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("razorpay", "RazorPay"), ("paypal", "Paypal")],
                        default="razorpay",
                        max_length=20,
                    ),
                ),
                ("payment_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("late", "Late"),
                            ("not_paid", "Not Paid"),
                        ],
                        default="not_paid",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="institutes.instituteprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_payments",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
