# Generated by Django 4.2.7 on 2023-12-11 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_studentpayment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentPayment",
        ),
    ]
