# Generated by Django 4.2.7 on 2023-12-04 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videorooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="room_link",
            new_name="room_code",
        ),
    ]
