# Generated by Django 4.2.7 on 2023-12-04 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videorooms", "0003_alter_classroom_room_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="room_code",
        ),
    ]
