# Generated by Django 4.2.7 on 2023-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videorooms", "0004_remove_classroom_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="password",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
