# Generated by Django 4.2.7 on 2023-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videorooms", "0005_alter_classroom_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="password",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
