# Generated by Django 4.2.7 on 2023-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videorooms", "0006_alter_classroom_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="room_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
