# Generated by Django 4.2.6 on 2023-10-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="max_otp_try",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.AddField(
            model_name="user",
            name="verification_sid",
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
