# Generated by Django 4.2.6 on 2023-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "unique_code"], name="accounts_us_email_60d782_idx"
            ),
        ),
    ]
