# Generated by Django 4.2.6 on 2023-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0003_alter_teacherprofile_user_delete_teacher"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(fields=["user"], name="teachers_te_user_id_839405_idx"),
        ),
    ]
