# Generated by Django 4.2.6 on 2023-10-12 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0004_teacherprofile_teachers_te_user_id_839405_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherprofile",
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
            },
        ),
    ]
