# Generated by Django 4.2.6 on 2023-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0003_rename_user_batch_institute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instituteprofile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="profile_picture",
            field=models.URLField(
                default="https://res.cloudinary.com/ddoz9iuvk/image/upload/v1699892423/vtsfxlwymkkbzefvmnvd.jpg"
            ),
        ),
    ]
