# Generated by Django 4.2.6 on 2023-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0004_remove_instituteprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instituteprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="instituteprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
