# Generated by Django 4.2.7 on 2023-11-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
        ("institutes", "0005_remove_instituteprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("requirements", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-Time"),
                            ("part-time", "Part-Time"),
                        ],
                        default="full-time",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[("remote", "Remote"), ("onsite", "Onsite")],
                        default="remote",
                        max_length=20,
                    ),
                ),
                ("salary", models.PositiveIntegerField(default=35000)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institute_jobs",
                        to="institutes.instituteprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("resume", models.URLField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applicant",
                        to="teachers.teacherprofile",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_application",
                        to="institutes.job",
                    ),
                ),
            ],
        ),
    ]
