# Generated by Django 4.2.7 on 2023-12-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0006_job_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("review", "Review"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
