# Generated by Django 4.2.7 on 2023-12-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0007_application_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="batch_fees",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="due_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="is_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="batch",
            name="scheduled_date",
            field=models.DateField(null=True),
        ),
    ]
