# Generated by Django 4.2.7 on 2023-12-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        (
            "institutes",
            "0008_batch_batch_fees_batch_due_date_batch_is_scheduled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="institute_payment_detail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.userpaymentdetail",
            ),
        ),
    ]
