# Generated by Django 4.2.7 on 2023-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0009_batch_institute_payment_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="fee_penalty",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
