# Generated by Django 4.2.7 on 2023-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0010_batch_fee_penalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_fees",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="batch",
            name="fee_penalty",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
