# Generated by Django 4.2.7 on 2023-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0011_alter_batch_batch_fees_alter_batch_fee_penalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="scheduled_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
