# Generated by Django 4.2.7 on 2023-12-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0013_remove_instituteprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instituteprofile",
            name="profile_picture",
            field=models.URLField(
                default="https://res.cloudinary.com/ddoz9iuvk/image/upload/v1699892423/vtsfxlwymkkbzefvmnvd.jpg"
            ),
        ),
    ]
