# Generated by Django 4.2.7 on 2023-11-23 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 11, 26)),
        ),
    ]
