# Generated by Django 4.2.7 on 2023-11-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_task_type_alter_taskassignment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("batch", "Batch"),
                    ("teacher", "Teacher"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
    ]
