# Generated by Django 4.2.7 on 2023-11-28 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_task_type_alter_taskassignment_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="tasks.task"
            ),
        ),
    ]
