# Generated by Django 4.2.7 on 2023-12-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_taskassignment_status_alter_task_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignment",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
    ]
