# Generated by Django 4.2.7 on 2023-12-09 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 12, 12)),
        ),
    ]
